name: app_worbun_1k
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.3
  audioplayers: ^6.0.0
  path_provider: ^2.1.4
  file_picker: ^8.0.5
  http: ^1.2.2
  ntp: ^2.0.0
  web_socket_channel: ^3.0.1
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons: 
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logoOf.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/logoOf.png
   - assets/
